version: '3'
services:
    nginx:
        image: nginx
        container_name: nginx
        ports: 
            - 80:80
        volumes: 
            - ./docker/nginx/:/etc/nginx/conf.d/
    
    python:
        build: ./docker/python
        container_name: python
        ports:
            - 8000:8000
        command: python main.py
        volumes:
            - ./py:/py